baseURL = 'https://chisite.github.io/paroleintransito/'
locale = 'it-it'
defaultContentLanguage = 'it'
title = "Chiara"
theme = 'PaperMod'

enableRobotsTXT = true
enableEmoji = true
pygmentsUseClasses = true

buildDrafts = false
buildFuture = false
buildExpired = false

[pagination]
  pagerSize = 10

[minify]
  disableXML = true

[params]
  env = "production"
  description = "Racconti e testi teatrali"
  defaultTheme = "auto"

  ShowReadingTime = true
  ShowWordCount = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = false
  ShowRssButtonInSectionTermList = true
  ShowToc = true
  TocOpen = false
  UseHugoToc = true
  comments = false

  [params.profileMode]
    enabled = true
    imageUrl = "images/chiara-background.jpeg"
    imageTitle = "Chiara"
    imageWidth = 500
    imageHeight = 500

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = false
